#!/bin/bash
# This script performs a get request

ERROR_FILE="error.log"
OUTPUT_FILE="data.json"
URL="https://pokeapi.co/api/v2/pokemon/pikachu"

curl --silent --write-out "%{http_code}" -o "$OUTPUT_FILE" "$URL" | grep "200" || {
    echo "Error: Can't GET data for url $URL"
    exit 1
}

echo "Data Saved successfully"
