#!/bin/bash
# This script performs a get request and extracts json data from it using jq

STDIN='data.json'

if [ ! -f "$STDIN" ]; then
    echo "$STDIN file not exist";
    exit 1
fi

name=$(jq -r '.name' $STDIN)
height=$(jq -r '.height' $STDIN)
weight=$(jq -r '.weight' $STDIN)
type=$(jq -r '.types.[0].type.name' $STDIN)

formatted_height=$(echo $height | awk '{print $1 / 10}')
formatted_weight=$(echo $weight | awk '{print $1 / 10}')

output="$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall.";

output=$(echo $output | sed 's/type/category/')

echo $output;
